### PR TITLE
Feature: New AST

### PR DESCRIPTION
**Pull request by CyberGsus**
# Moving to a brand new AST to improve performance and user experience

The current AST involves a lot of copying, while giving almost no support for analysis nor error reporting to the user, and the interpreter
can't handle errors properly. I propose these changes:

- [x] Create a better AST, that includes source information and goes deeper into enumerations before having to handle the source, and enabling later static analysis passes like checking function names, available variables and so on, so the run-time errors are reduced to I/O errors when reading each file/directory.
- [x] Modify the interpreter so it works with this new AST, with the current error handling.
- [x] Replace all `String`s in the AST for `&'source str` 
~~- [ ] Add AST passes to convert function calls and variables to enums and structs, and verify the coherence of the conditions, so that most of the script errors are caught before execution.
The coherence conditions will be written as this pull request advances and we can comment what things will be allowed and what will be not.~~ This no longer applies, since the AST is fully implemented. The checks will be on extra features later and decisions on it will change how the language works.

Note that this doesn't change the scripting language nor the overall interpreter design. Even though it introduces lots of changes, the execution order of the script is preserved,
and it majorly helps separate the errors internally and removes a lot of string manipulation, specially inside the interpreter.

### CODE REVIEW

**Comment by Alonely0** [comment]
Okay. I love it, even though the parser now is much more complex, error messages are better (as seen in the discord), and it'll also improve the interpreter, so I like it. This afternoon I'll start reviewing the code, but could you put more comments in the code? There aren't too many ones.

**Comment by CyberGsus** [comment]
I'm going to have to do quite the change for the interpreter to work with the new AST. I'll be adding documentation to the parser methods and the AST types for internals, but I don't know what else should be explained. The parser has a different structure, with a centric state that gives tokens and errors, and the types implement the parsing. That way the code can be separated more efficiently. PS: thank you for adding WIP

**Comment by CyberGsus** [comment]
The interpreter is now fully integrated! 🎉 Now the last thing is to bootstrap a pass to the AST to check for expression type errors or missing function arguments

**Comment by CyberGsus** [comment]
Hmm, looks like the README thing is not mine....

**Comment by Alonely0** [comment]
Well... I love it. There's only one problem, that I cannot use symbols in strings anymore:
image
image
image
and more. I'll put colors in error messages too.


Strings in function arguments should be everything that is not a parenthesis, and strings in conditionals should be everything that is not an operator or a curly bracket

**Comment by CyberGsus** [comment]
Interesting.... thanks

**Comment by CyberGsus** [comment]
Looks like updating the regex token and introducing actual contexts to the parser worked. I changed the regex token to be the same as you had set it. Let me check that the messages still have the correct context

**Comment by CyberGsus** [comment]
hmm, it doesn't really work...
image
This should have failed

**Comment by Alonely0** [comment]
I finished the colors.
This is how it looks like in my gruvbox alacritty:
image
and this is how it looks like in a default alacritty (by default it has a nord-ish colorscheme):
image

**Comment by CyberGsus** [comment]
Cool! Make a PR to the fork then :)

**Comment by Alonely0** [comment]
i cant, you have to give me write access by checking the box of "Allow edits by maintainers"
image

**Comment by CyberGsus** [comment]
Hmm, I get why it doesn't fail in my example.... Weird though

**Comment by CyberGsus** [comment]
in my fork

**Comment by Alonely0** [comment]
i cant

**Comment by CyberGsus** [comment]
Can't you open a PR to my fork?

**Comment by CyberGsus** [comment]
Ok, I'll permit the edit. Push it here and I'll merge it with my version

**Comment by Alonely0** [comment]
done

**Comment by CyberGsus** [comment]
Hmmm... I would leave the snippet line white though, for clarity. Will be working on the error so that annotatinons can be added separately

**Comment by CyberGsus** [comment]
image
This is what I suggest

**Comment by Alonely0** [comment]
oh. we have a problem...
image

**Comment by CyberGsus** [comment]
You can ditch anything that wasn't from here, since I had to rework it almost entirely

**Comment by CyberGsus** [comment]
Merged!

**Comment by Alonely0** [comment]
debug messages are gone. Do you think they're necessary or can/should be deleted?

**Comment by Alonely0** [comment]
i had an orgasm while reading this error message, the parser is amazing (compared to the legacy)
image

**Comment by Alonely0** [comment]
im testing the parser, if all goes ok this will get merged asap (but we still  have to discuss how should we manage runtime logs)

**Comment by Alonely0** [comment]
Ok, I have found something. In the legacy parser, all these would be resolved at runtime like this:
  * `copy(@path, /tmp/@name)` => `copy(@path, /tmp/<filename>)`
  * `print(@path.file)` => `print(<filepath>.file)`
  * `print(@parent/@name)` => `print(<parentdir>/<fiename>)`

But in the actual parser it gets treated as normal text that just has an `@`, so it's completely ignored.

**Comment by CyberGsus** [comment]
I left out runtime logs because I was restructuring things over and over, we can add them back sure :)

**Comment by CyberGsus** [comment]
> Ok, I have found something. With the legacy parser, all these would be resolved at runtime like this:
>   * `copy(@path, /tmp/@name)` => `copy(@path, /tmp/<filename>)`
>   * `print(@path.file)` => `print(<filepath>.file)`
>   * `print(@parent/@name)` => `print(<parentdir>/<fiename>)`
> 
> But in the actual parser it gets treated as normal text that just has an `@`, so it's completely ignored.

Interesting... I found the error. Turns out that the identifier is taking over the variable in the lexer... As the parser is already taking unidentified variables as identifiers, I'll turn off the `@` for the identifier. It's not perfect, specially for the condition expressions (there, sequential strings/vars don't get mashed up, although supporting it will remove redundant code)

**Comment by CyberGsus** [comment]
Also, with the new parser the conditional is optional: if you want a block to run without filter, specify the block without the condition `{ print(@name.file) }`

**Comment by CyberGsus** [comment]
image
Found another parser bug, it should've inferred context there. I removed that because I thought that it couldn't happen...

**Comment by CyberGsus** [comment]
Hmmm, I've had an idea, let me know what you think: we can make the expression strings do the same interpolation thing as the argument ones, for consistency. Then we can eliminate the regex token, and convert to the regex type after parsing (during the validation pass, which we do at runtime for the moment). For this to work properly though, the 'pattern side' of the match operators must be always the same, I suggest it being right as `@name ~= *.tar.gz` will be read as `name matches "*.tar.gz"`

**Comment by Alonely0** [comment]
Sure, let's move forward with that

**Comment by CyberGsus** [comment]
Hmm. When converting to regex, will we make lookups available? This is fairly easy to decide right now, when we have runtime checking. But for static checking, having a binding there is kind of difficult to look at.. most of them have a valid regex format, but the validation process is also used to compile down things like regexes and parsing the numbers so that the heavy lifting doesn't have to be re-done on each run (which it is for numbers, strings and bools. Regexes are computed currently by the parser.)

**Comment by CyberGsus** [comment]
Validating contexts is used exactly for this, because if there is an invariant, you can do the appropiate thing once and remove the deciding from the runtime

**Comment by CyberGsus** [comment]
image
Since it knows the variable name statically, I decided to put it in the invalid specifier message as well :)

**Comment by CyberGsus** [comment]
I think this should be the final thing, the new AST is complete. Make sure to add the logging messages wherever you need them (the runner functions are at `ast/*::run_*`, in the `target`, `script`, and `call` modules)

**Comment by CyberGsus** [comment]
Also, when you merge, make sure  to squash everything into one commit (use `git rebase -i new-parser` and replace `pick` with `squash`)

**Comment by CyberGsus** [comment]
Now that I see it, dates are not properly checked by this new version: they don't support the relative operators... I'm going to work on that

**Comment by Alonely0** [comment]
i found a bug
image

**Comment by CyberGsus** [comment]
Ok, that's an easy fix. Thank you.

**Comment by Alonely0** [comment]
still panics

**Comment by CyberGsus** [comment]
I didn't fix it yet... I fixed the last thing I mentioned. One at a time :)

**Comment by Alonely0** [comment]
:)

**Comment by CyberGsus** [comment]
There's a problem... @#name shouldn't be allowed.

**Comment by CyberGsus** [comment]
The problem is that if we allow things like that, then we lose the ability to alert the user that a lookup is not available or (in this case) its specifier is not available

**Comment by CyberGsus** [comment]
if you want random things starting with an at to not be mistaken by variables, while maintaining the perks of the context-aware parser, I suggest adding a proper string (between quotes) token to the language.

**Comment by CyberGsus** [comment]
we *can* make the parser accept that without changes to the AST, it's not a big problem, and I've already been working on a solution. But the user would lose a lot in not knowing if their code was accepted the same way they were thinking

**Comment by Alonely0** [comment]
Well, whenever possible, I want to maintain the language without quotes for delimiting strings. I prefer to make things starting with an `@` trigger an error if aren't valid variables

**Comment by CyberGsus** [comment]
Then things like `@a` won't be available (yet). As said, we can make an extension to the language with a "raw" string literal in the future.

**Comment by CyberGsus** [comment]
What we have now is that variables whose *name* (the thing before the `=`, if any) is not recognized pass as normal strings and the error only happens with specifiers. If you think that's good we can leave it, or add a restriction to make not recognized variables trigger an error as a whole

**Comment by Alonely0** [comment]
i like how it's now

**Comment by Alonely0** [comment]
> we can make an extension to the language with a "raw" string literal in the future
what about a scape token `\` that treats the next token as txt instead?

**Comment by Alonely0** [comment]
this could be used for log messages
https://github.com/zhiburt/tabled

**Comment by CyberGsus** [comment]
Please remit to open PRs on the branch at my fork if you want to do more changes. If you want to add unrelated changes (like you've done now) consider doing so after we've merged this PR.

**Comment by Alonely0** [comment]
There are some TODOs on the codebase, but do you think It's ready for being merged?

**Comment by CyberGsus** [comment]
I'll resolve some of the TODOs

**Comment by CyberGsus** [comment]
> > we can make an extension to the language with a "raw" string literal in the future
> 
> what about a scape token `\` that treats the next token as txt instead?

Then how'd you specify paths in windows and so on?... The problem with accepting any character is that you can't set escapes.

**Comment by Alonely0** [comment]
> Then how'd you specify paths in windows and so on?... The problem with accepting any character is that you can't set escapes.

you just escape it `\\`. A lot of win programs show paths like that anyway, is not something very odd.

**Comment by CyberGsus** [comment]
I will now check that the documentation is correct.

**Comment by CyberGsus** [comment]
wait, the reader that I implemented is very bad for big files. I will switch to a bufreader

**Comment by CyberGsus** [comment]
> > Then how'd you specify paths in windows and so on?... The problem with accepting any character is that you can't set escapes.
> 
> you just escape it `\\`. A lot of win programs show paths like that anyway, is not something very odd or strange.

Ok, we can hande it in a separate PR

**Comment by CyberGsus** [comment]
Although I think it is more intuitive to add a literal string like zsh's `'`. There is no doubt that it is a string and prevents things like parens and so on getting in your way

**Comment by Alonely0** [comment]
> Although I think it is more intuitive to add a literal string like zsh's `'`. There is no doubt that it is a string and prevents things like parens and so on getting in your way

well, voila code should be inside bash's & zsh's literal string for avoiding edge cases where the shell makes something weird inside the code (for example when using `$` in strings), so those tokens would have to be escaped (or just use double quotes instead). usually you'd not escape much characters, that's why I prefer the ancient backslash as escaping symbol.

**Comment by CyberGsus** [comment]
OK, we can merge this PR. I've kept some TODOs with ideas I've had of doing, but that don't really deserve a separate issues

**Comment by Alonely0** [comment]
I'll read all the code (i have read like 70%) and tomorrow this should be merged

**Comment by Alonely0** [comment]
I'll have to get used to the new interpreter structure, but I love it, everything. A lot of thanks for contributing, I hope I can chat with you in the discord if I have any doubt.

**Pull request merged**
