### PR TITLE
ci(actions): improve build workflow

### PR DESCRIPTION
**Pull request by afgalvan**
This pull request changes or add:

Changes:

- Specify which os version to use, this will avoid a build error in case of an update on the latest version of the runner.

---

Add:

- I created a formatting workflow that makes commits for formatting code during the action run on pull requests.
- Caching rust for improving next workflows runs.

### CODE REVIEW

**Comment by Alonely0** [comment]
format action fails
image

**Comment by Alonely0** [comment]
Remember to change the badges in the readme

**Comment by afgalvan** [comment]
I'll check it in a minute, and change the readme badges too

**Comment by afgalvan** [comment]
So, this error happens to be a GitHub bug, because it works in my fork as explains in [this issue](https://github.com/actions/first-interaction/issues/10).

The workflow fails because the formatting action needs GitHub credentials to make commits, and it's trying to use **my** credentials to commit in **your** repository, and as I don't have any permissions, it fails, so basically the only solution is to merge the pull request so it uses your credentials, not mines.

**Comment by Alonely0** [comment]
Ok so if you fix the badges of the README your pull request will be merged

**Comment by afgalvan** [comment]
So, I had to add a YAML config for each OS again in order to have an individual CI badge

**Pull request merged**
